blank_issues_enabled: true # Enabled for now until all issue templates are added
contact_links:
  - name: BeatTogether Community Discord
    url: https://discord.com/invite/gezGrFG4tz
    about: Please ask and answer questions here.
